# Generated by Django 5.2 on 2025-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clg_name', models.CharField(max_length=50)),
                ('Countryname', models.CharField(default='India', max_length=30)),
                ('Statename', models.CharField(default='Gujarat', max_length=30)),
                ('Cityname', models.CharField(default='Ahmedabad', max_length=30)),
                ('ContactNo', models.BigIntegerField()),
                ('EmailId', models.EmailField(max_length=254)),
                ('AdministrationName', models.CharField(max_length=50)),
                ('Administration_No', models.BigIntegerField()),
                ('Approval', models.BooleanField(choices=[(1, True), (2, False)], default=False)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
