# Generated by Django 5.2 on 2025-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesmodel',
            name='Approval',
            field=models.BooleanField(choices=[(1, True), (2, False)], default='False'),
        ),
    ]
