# Generated by Django 5.2 on 2025-04-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0002_alter_collegesmodel_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesmodel',
            name='Approval',
            field=models.BooleanField(choices=[(1, True), (2, False)], default=False),
        ),
    ]
