# Generated by Django 5.2 on 2025-04-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0003_alter_collegesmodel_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesmodel',
            name='Approval',
            field=models.BooleanField(default=False),
        ),
    ]
