# Generated by Django 5.2 on 2025-04-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0004_alter_collegesmodel_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10)),
                ('BirthDate', models.DateField()),
                ('Faculty_phone_no', models.BigIntegerField(max_length=10)),
                ('FacultyEmail', models.EmailField(max_length=254)),
                ('FacultyAddress', models.TextField(max_length=250)),
                ('EntrolmentNo', models.CharField(max_length=20)),
                ('DepartMent', models.CharField(max_length=30)),
                ('Document', models.FileField(upload_to='Faculty_documents')),
                ('Approval', models.BooleanField(default=False)),
                ('Time', models.DateField(auto_now=True)),
                ('CollegeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.collegesmodel')),
            ],
        ),
    ]
