# Generated by Django 5.2 on 2025-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0005_facultymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='Faculty_phone_no',
            field=models.BigIntegerField(),
        ),
    ]
