# Generated by Django 5.2 on 2025-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0006_alter_facultymodel_faculty_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
