# Generated by Django 5.2 on 2025-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0007_alter_facultymodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='Document',
            field=models.ImageField(upload_to='Faculty_documents'),
        ),
    ]
