# Generated by Django 5.2 on 2025-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0011_alter_facultymodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
