# Generated by Django 5.2 on 2025-04-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0012_alter_facultymodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=20)),
                ('BirthDate', models.DateField()),
                ('Student_No', models.BigIntegerField()),
                ('Student_Emailid', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Student_EntrollNo', models.CharField(max_length=20)),
                ('StudentCourse', models.CharField(max_length=30)),
                ('StudentSemester', models.CharField(max_length=30)),
                ('Approval', models.BooleanField(default=False)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.collegesmodel')),
            ],
        ),
    ]
